#!/usr/bin/python
import rpm

def printresult (name, mi):
    print name
    for h in mi:
        print "\t%(name)s-%(version)s-%(release)s" % h

ts = rpm.ts()
db = ts.openDB()
printresult ('provides', ts.dbMatch ('providename', 'libc.so.6'))
printresult ('requires', ts.dbMatch ('requirename', 'libGL.so.1'))
printresult ('obsoletes', ts.dbMatch ('obsoletes', 'gimp-data-min'))
printresult ('name', ts.dbMatch ('name', 'gimp'))
printresult ('basenames', ts.dbMatch ('basenames', '/etc/passwd'))

#print db[db.findbyname ('gimp')[0]]['name']

