CREATE TABLE IF NOT EXISTS Packages (
  i	INTEGER PRIMARY KEY NOT NULL,
  h	BLOB NOT NULL
);
CREATE TEMP TRIGGER IF NOT EXISTS insert_Packages AFTER INSERT ON Packages
  BEGIN
    INSERT INTO Nvra (k,v)	VALUES ( new.h, new.rowid );
  END;
CREATE TEMP TRIGGER IF NOT EXISTS delete_Packages BEFORE DELETE ON Packages
  BEGIN
    DELETE FROM Nvra WHERE v = old.rowid;
  END;

CREATE TABLE IF NOT EXISTS Nvra (
  k	TEXT PRIMARY KEY NOT NULL,
  v	INTEGER REFERENCES Packages(i) ON UPDATE RESTRICT ON DELETE RESTRICT
);
