.\" rpmconstant - provides RPM API constants
.TH rpmconstant 8 "21 July 2007" "rpm5.org" "RPM Package Manager"
.SH NAME
rpmconstant \- Provides RPM API constants.
.SH SYNOPSIS
\fBrpmconstant\fP [OPTION...]
.SH DESCRIPTION
\fBrpmconstant\fP provides RPM API constants (usually to language bindings).
.SH SEE ALSO
.IR rpm (8)
.SH AUTHOR
.nf
Nanar <nanardon@zarb.org>
.fi
