#!/bin/sh
#
# Gets file list on standard input and RPM_BUILD_ROOT as first parameter
# and searches for omitted files (not counting directories).
# Returns it's output on standard output.
#
# filon@pld.org.pl

RPM_BUILD_ROOT=`echo $1 | sed 's://*:/:g'`

if [ ! -d "$RPM_BUILD_ROOT" ] ; then
	cat > /dev/null
	exit 1
fi

[ "$TMPDIR" ] || TMPDIR=/tmp
FILES_DISK=`mktemp $TMPDIR/rpmXXXXXX`
FILES_RPM=`mktemp $TMPDIR/rpmXXXXXX`

find $RPM_BUILD_ROOT -type f -o -type l | \
	sed 's://*:/:g' | \
	sed "s,$RPM_BUILD_ROOT/dev/.*,," | \
	LC_ALL=C sort > $FILES_DISK
sed 's://*:/:g' | LC_ALL=C sort -u > $FILES_RPM

diff "$FILES_DISK" "$FILES_RPM" | grep "^< " | cut -c3- | sed -e "s#^$RPM_BUILD_ROOT#   #g"

rm -f $FILES_DISK
rm -f $FILES_RPM
