#!/bin/sh

[ $# -ge 1 ] || {
    cat > /dev/null
    exit 0
}

case $1 in
-P|--provides)
    while read possible
    do
	case "$possible" in
	*.la)
	    if grep -iq '^# Generated by ltmain.sh' "$possible" 2> /dev/null ; then
		echo "libtool($possible)"
	    fi
	    ;;
	esac
    done
    ;;
-R|--requires)
    while read possible ; do
	case "$possible" in
	*.la)
	    for dep in `grep ^dependency_libs= "$possible" 2> /dev/null | \
			sed -r -e "s,^dependency_libs='(.*)',\1,g"`
	    do
		case "$dep" in
		/*.la)
		    echo "libtool($dep)"
		    ;;
		esac
	    done
	    ;;
	esac
    done
    ;;
esac
