#!/bin/sh

prefix=/usr/lib/rpm
exec_prefix=/usr/lib/rpm
exec_prefix_set=no
includedir="${prefix}/include"
libdir="${prefix}/lib"
version=1.9.1
platform=i686-linux

usage="\
Usage: ruby-config [--prefix] [--exec-prefix] [--version] [--cppflags] [--libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo "${version}"
      ;;
    --cppflags)
      echo "-I${includedir}/ruby-${version}/ -I${includedir}/ruby-${version}/${platform}/"
      ;;
    --libs)
      echo "-L${libdir}/ -lruby-static -lcrypt"
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
